from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from .views import (UserProfileView,
                    ApiKeyList,
                    UserInfoList,
                    UserInfoDetail,
                    GoogleLogin,
                    FacebookLogin,
                    ForgotPasswordAPI,
                    ResetPasswordAPI, ChangePasswordAPI, CustomRegisterView,
                    CheckoutSessionView, CancelSubscriptionView,
                    NotificationListView, StripePaymentStatusView,
                    NotificationAllReadUpdateView, NotificationReadUpdateView,
                    PaypalPaymentStatusView, GetSubscriptionView, SubscriptionPlansEnvView)


urlpatterns = [
    path("login/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path('profiles/', UserInfoList.as_view()),
    path('profiles/<str:pk>/', UserInfoDetail.as_view()),
    path("profile/api-keys", ApiKeyList.as_view(), name="user_api_keys"),
    path('', include('allauth.urls')),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('auth/facebook/', FacebookLogin.as_view(), name='fb_login'),
    path('forgot-password/', ForgotPasswordAPI.as_view(), name='forgot_password'),
    path('reset-password/', ResetPasswordAPI.as_view(), name='reset_password'),
    path('change-password/', ChangePasswordAPI.as_view(), name='change_password'),
    path('registration/', CustomRegisterView.as_view(), name='register'),
    # path('v1/subscription/plans/', SubscriptionPlansView.as_view(), name='stripe_products'),
    path('v2/subscription/plans/', SubscriptionPlansEnvView.as_view(), name='stripe_products'),
    path('stripe/checkout-session/', CheckoutSessionView.as_view(), name='stripe_checkout-session'),
    path('cancel-subscription/', CancelSubscriptionView.as_view(), name='cancel_subscription'),
    path('current-subscription/', GetSubscriptionView.as_view(),
         name='current_subscription'),
    # path('stripe/subscriptions/', ListAllSubscriptionsView.as_view(), name='stripe_subscriptions'),
    # path('stripe/cards/', StripeCardsView.as_view(), name='stripe_cards'),
    # path('stripe/primary-card/', SetPrimaryCardView.as_view(), name='stripe_primary_card'),
    path('stripe/payment/status/', StripePaymentStatusView.as_view(), name='stripe_payment_status'),
    path('notifications_1/', NotificationListView.as_view(), name='notification-list'),
    path('notifications_2/<str:filter_value>/', NotificationListView.as_view(), name='filtered-notification-list'),
    path('notifications/read/<uuid:notification_id>/',
         NotificationReadUpdateView.as_view(), name='notification_read'),
    path('notifications/all/read/', NotificationAllReadUpdateView.as_view(),
         name='notifications_read_all'),
    # path('paypal/plans/', PayPalPlansView.as_view(), name='paypal-plan-list'),
    # path('paypal/subscription/<str:subscription_id>/', PaypalSubscriptionView.as_view(),
    #      name='paypal-subscription-details'),
    path('paypal/payment/status/', PaypalPaymentStatusView.as_view(), name='paypal-payment-status'),

]
