# Generated by Django 4.1.7 on 2023-04-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="free_trail",
            new_name="free_trial",
        ),
    ]
