# Generated by Django 4.1.7 on 2023-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nftion", "0002_rename_status_nft_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="average_hold_duration",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="nft",
            name="average_sale_duration",
            field=models.DurationField(null=True),
        ),
    ]
